apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml --namespace=gurwls0122 --controller statefulset convert
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: gurwls0122
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  serviceName: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/dockertest14-default: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: kluster
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
          image: mysql:latest
          name: mysql
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          resources: {}
      restartPolicy: Always
  updateStrategy: {}
status:
  availableReplicas: 0
  replicas: 0
