apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml --namespace=gurwls0122 --controller statefulset convert
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-app
  name: spring-app
  namespace: gurwls0122
spec:
  clusterIP: None
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: spring-app
  type: ClusterIP
status:
  loadBalancer: {}
